### ISSUE TITLE
The todo's card background color is missing

### ISSUE THREAD

**Issue by tkgroot** [front-wings/todo-app#13] opened 2021-05-06 06:26 UTC
The card background isn't white, but should be.

**Comment by tkgroot** [comment] 2021-05-06 06:26
Somehow an error creeped into the styles of `card__content` which changes the background color.
The color should match either `#fff` or `white`

**Comment by fswijmans** [comment] 2021-05-06 08:51
Hi Tobias,

I see this had the label duplicate but then I found out that you removed the labels? So is this really duplicate or not?

**Comment by tkgroot** [comment] 2021-05-06 08:53
Its really a duplicate. Sorry about the confusion. I needed to double check

**Comment by ruphin** [comment] 2021-05-06 08:54
I think this is a duplicate of #3

**Comment by fswijmans** [comment] 2021-05-06 09:12
Ok thanks!

**Closed as completed** 2021-05-06 09:37 UTC
Labels: bug, duplicate, good first issue
